### ISSUE TITLE
onClose program - Warn Unsaved Changes

### ISSUE THREAD

**Issue by bazzinotti** [bazzinotti/snestracker#105]
If there are any unsaved changes, warn the user on quit with a dialog box! "You have unsaved changes! Are you sure you want to quit??" (Yes|NO) (Boy I'm so glad I have those implemented now :joy: )

What constitutes "changes"?

- instrument modifications
- Sample modifications
- SongSettings modifications
- Pattern
- PatternSequencer

**Comment by RowanDDR** [comment]
![image](https://user-images.githubusercontent.com/6626459/86929484-d174c000-c12d-11ea-8db3-8003babc66c0.png)
This is GREAT! 🥳

Improvements I suggest are:

Instead of `Cancel` `No` `Yes` I propose `Save` `Save As` `Cancel` ... because, its a more intuitive order (I think), a 'No' button is not needed as it does the same thing as 'Cancel button', and `Save as` because users may not want the save to overwrite the instance they were working on.

**Comment by bazzinotti** [comment]
> Little improvements I suggest are:
> Instead of Cancel No Yes, how about Save Save as No instead?

I feel you. At the same time, the dialog box models countless other programs used on the daily. Think word processors, music programs, most things that involve the user working on a file. I like that consistency. Plus, with your proposed buttons there is no way to get back to the program from the dialog. In order to get back without losing my changes, I would be forced to save or save as, then reopen the program and finally make my adjustment and then re-save again.

The one convenience that your proposal provides is a 'Save As' directly from the dialogue. As much I also want that to be there, 4 buttons seemed like a lot to me. In this case, you would just hit Cancel and then File->Save as; still quick enough. So unless there is another way, I wont change the current dialog box.

> I noticed that if choosing "Open ST Song" after making changes, you don't sometimes don't get prompted to save your work.

This is probably already fixed in the upcoming release.

**Comment by RowanDDR** [comment]
OK, fair. 👍

But regarding the button order, I'd still say having `Cancel` as the first option is not in line with other programs, not in Windows at least.

e.g. 
![image](https://user-images.githubusercontent.com/6626459/86981477-9babf780-c17e-11ea-83e9-e0f6a32310ee.png)

**Comment by bazzinotti** [comment]
I appreciate your attention to detail! It seems there is leeway for button ordering, given this pic from the popular cross-platform audio program Audacity.
![audacity-close-buttonorder](https://user-images.githubusercontent.com/2224787/86981625-1c55fe00-c155-11ea-8c6a-fe50242aab59.png)

**Comment by RowanDDR** [comment]
Checkmate!♟️😂  I wonder if that's mac logic vs PC logic. A battle that can't be settled..
