### ISSUE TITLE
[Bug] Program fails to launch if Steinberg's The Grand 2 is open at the same time.

### ISSUE THREAD

**Issue by RowanDDR** [bazzinotti/snestracker#106]
Program fails to launch if you have Steinberg's The Grand 2 open at the same time. It seems to quit immediately, in the same fashion as https://github.com/bazzinotti/snestracker/issues/76

Windows 10.

**Comment by bazzinotti** [comment]
This touches upon another thing I'm about to fix which was that windows builds didn't show debug output. I'll send you a build that has debug output. (note to self: add -mconsole as per 
https://stackoverflow.com/questions/34539135/how-do-i-print-to-the-console-while-an-sdl-2-program-is-running)
When you get the build, run the command like `st.exe > log.txt 2>&1`. Then copy paste contents of the `log.txt` here.

**Comment by bazzinotti** [comment]
Here's the build [snestracker-STI-debug-4d06edc7-Win64.zip](https://github.com/bazzinotti/snestracker/files/4833188/snestracker-STI-debug-4d06edc7-Win64.zip)

**Comment by bazzinotti** [comment]
Here's the screenshots from RowanDDR (from Discord)

![st-thegrand-crash](https://user-images.githubusercontent.com/2224787/85798516-9aed7d00-b70b-11ea-941a-1c968e89421c.png)

First off, what exactly is generating those strange characters seen after the error? I'll have to take a look at the what code producing this error.

Also, After some googling, I found that error string associated with `ffplay` a couple years ago. Users experienced success manually setting their SDL audio driver to `directsound`. As a temporary fix I had Rowan try this. But he seems to not have it installed, as seen below. 

![st-thegrand-crash2](https://user-images.githubusercontent.com/2224787/85799051-970e2a80-b70c-11ea-89e3-bf64a7ec4336.png)

Besides, users should not be forced to install DirectSound just to use this app (although it could be a workaround for the time). I'll have to get to the bottom of this.


### Unrelated note on the debug console

The way the debug console is spawned  seems to cause the pipe command options not to work. The log.txt remains at 0 bytes. Using the same stackoverflow link above, there is a way to (without `-mconsole`) insert some windows specific code to spawn a console. This (I hope) would allow pipe redirecting to work. For now, we can copy paste the console output or a screenshot. That is better than nothing.

**Comment by bazzinotti** [comment]
### Possible Workaround #2

Confirm that snestracker is not running. Then,  open up Grand 2. Now, delete snestracker's Preferences.ini file as follows:
```
rm C:\Users\Kaby3\AppData\Roaming\Black_Hole_Studios\SNES_Tracker\Preferences.ini
```

Now run snestracker and see if it doesn't crash :wink:

**Note to self**: If it works, it demonstrates a need to redesign how snestracker opens audio devices based on previously saved audio device name.

**Comment by RowanDDR** [comment]
I deleted Preferences.ini, but SNES Tracker still crashes at launch (then remains active in the background with high CPU usage).
