### ISSUE TITLE
[Steinberg Grand 2 only] Remnant windows processes

### ISSUE THREAD

**Issue by bazzinotti** [bazzinotti/snestracker#107]
Possibly caused by #106 (Using Steinberg's Grand 2 while opening snestracker causes silent failure).

Here's a screenshot from @RowanDDR
![st-processes](https://user-images.githubusercontent.com/2224787/85800361-d178c700-b70e-11ea-92a0-d92b6a20ee5e.png)

Here we can see several remnant processes.
I have just verified this is not present on Linux under normal circumstances.

**Comment by bazzinotti** [comment]
@RowanDDR Could those be from the "crash"es of #106? The only way to test it is to kill them all, then under normal circumstances (Steinbrenner Grand 2 closed) run and quit the app. Does it remain in the task manager? If not, then good sign. It must mean the steinbrenner crash caused them.

**Comment by RowanDDR** [comment]
Close behavior is fine under normal circumstances. The problem only occurs when The Grand 2 is running.
