### ISSUE TITLE
[BUG] Unsaved Changes not always detected

### ISSUE THREAD

**Issue by RowanDDR** [bazzinotti/snestracker#124]
Steps to reproduce: Open a file, DELETE a few notes, then select another file from the RECENTS menu. You will not be prompted to save your unsaved changes.

Using SNES Tracker patreon version 0.1.1, PC build, Windows 10.

**Comment by bazzinotti** [comment]
Fixed on my local v0.1.2 branch ;)

**Comment by RowanDDR** [comment]
I have tested this in v0.2.0 and can confirm it's fixed. Thanks. 👍
