### ISSUE TITLE
c700 brr file incompatibility

### ISSUE THREAD

**Issue by bazzinotti** [bazzinotti/snestracker#72]
[C700](http://picopicose.com/how_to_use_the_c700_eng.html) outputs an additional 2 bytes before the actual BRR sample. This is probably the loop address. Unfortunately it's no straightforward to recognize the raw data from a normal BRR file. To consider compatibility, 

The first byte could be compared to typical starting BRR header block. Then check the 3rd byte if its a typical BRR header block. Certain combinations of this check would produce guaranteed results. In ambiguous cases, warn the user to make a decision to load one way or the other.

**Comment by Exodustx0** [comment]
The first 2 bytes of BRR files exported by C700 are the AddmusicM header, which indicates the offset, in bytes (excluding header), for where the loop starts. Recognizing this format is easy enough by checking the file's filesize. If filesize modulo 9 = 2, it has the header. If 0, it doesn't. And if any other value, it's a borked sample.

**Comment by bazzinotti** [comment]
I appreciate you reaching out. of course! Thanks for the brilliant tip (how could I miss it? 😄 ).
